version: '3.8'
services:
  cryptomator-vault-server:
    image: cryptomator-vault-server
    build: .
    ports:
      - "8000:8000"
    environment:
      - VAULTS_CONFIG=/config/vaults.yaml
    volumes:
      - /path/to/vaults.yaml:/config/vaults.yaml:ro
      - /path/to/vaults:/data/vaults/
    user: "33:33"  # Replace with desired UID:GID
    # Required for mounting the decrypted vaults devices inside the container
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined    
